### ISSUE TITLE
Keys are duplicated again... Should be use Tabler!

### ISSUE THREAD

**Issue by Apricot-ale** [mihuan-0/G.M.-Cold-War-Germany---Community-Language-Pack#7]
Key ID="STR_DN_GM_GE_BGS_OLI" are duplicated again!!!

I removed this error because it happened the last time I did a split update, but it's happening again. Someone seems to have added it in vain during the last merge.

Line 2684: is WRONG. It's not match with original localize.
```
			<Key ID="STR_DN_GM_GC_BGS_OLI">
				<Original>East Germany (Borderguards)</Original>
				<English>East Germany (Borderguards)</English>
				<German>DDR (Grenzschutz)</German>
				<Chinesesimp>东德(边防部队)</Chinesesimp>
				<Korean>동독(국경 경비대)</Korean>
				<Russian>ГДР (Пограничники)</Russian>
			</Key>
```

Line 2788: is RIGHT. It's match with original localize.
```
			<Key ID="STR_DN_GM_GC_BGS_OLI">
				<Original>East Germany (Olive)</Original>
				<English>East Germany (Olive)</English>
				<German>DDR (Oliv)</German>
				<Chinesesimp>东德(橄榄)</Chinesesimp>
				<Korean>동독 (올리브)</Korean>
				<Russian>ГДР (Оливковый)</Russian>
			</Key>
```

![image](https://user-images.githubusercontent.com/50947830/175871312-39a73fb1-93ee-450d-b175-7a5e50615baf.png)

Such errors can be avoided by using support software such as Tabler and spreadsheet (Excel).
Should be use Tabler.
https://github.com/bux/tabler
I using spreadsheet like this
https://docs.google.com/spreadsheets/d/1V7YlwrlFO2fTBQzKDTI-4ZTp--Bwaqnf97Y4wj2AI40/edit?usp=sharing

Translation procedure using Tabler and spreadsheet (recommended)

1. Get the latest files from GitHub.
2. Open the "\G.M.-Cold-War-Germany---Community-Language-Pack\Addons\gm_languages_additional" folder in Tabler.
3. Wait for a long load. This is due to the huge amount of translations in one file(folder). Further division is necessary to reduce the loadtime.
3A. Error when loading is basically occurs when there are duplicate keys. (This case!)
4. Click(select) the language name ID on Tabler and press Ctrl + C to copy.
5. Select a column in the spreadsheet(Excel) and press Ctrl + V to paste.
6. Translate.
7. Select a column in the spreadsheet(Excel) and press Ctrl + C to copy.
8. Click(select) the language name ID on Tabler and Ctrl + V to paste.
9. The updated part is displayed in green.
10. When the check is complete, save from File and exit when the progress bar disappears. Please note that at the end, a warning will be displayed even if it is saved.
11. Just in case, open the file directly with notepad etc. and check it.
11A. If the line breaks are strange, it means that unnecessary text is included in addition to the Key. so remove the unnecessary text to fix this. (I had a problem when I publicized on GitHub before)
12. Upload and finish.

**Comment by mihuan-0** [comment]
Need to write a feedback to get
Bohemia Interactive and
Vertexmacht aware of the error. This will solve the problem once and for all.

**Comment by mihuan-0** [comment]
I use winmerge😀
 https://github.com/WinMerge/winmerge

**Comment by mihuan-0** [comment]
https://feedback.bistudio.com/T166277

**Comment by Apricot-ale** [comment]
ahh, so it's a vertexmacht's mistake, ok.
